[package]
name = "frostbite-modelkit-tools"
version = "0.0.0"
edition = "2021"

[dependencies]
futures = "0.3"
solana-client = "1.14"
solana-sdk = "1.14"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
